export type SkillClusterData = {
  id: string;
  name: string;
  direction: 'left' | 'right';
  evidence?: string;
  skills: string[];
};

export const skillsData: SkillClusterData[] = [
  {
    id: 'ai-ml',
    name: 'AI / Machine Learning',
    direction: 'right',
    skills: [
      'Python',
      'scikit-learn',
      'Classical ML',
      'Feature Engineering',
      'Feature Selection',
      'Model Evaluation',
      'Hyperparameter Tuning',
      'Model Deployment',
      'ML Pipelines',
    ],
  },
  {
    id: 'deep-learning',
    name: 'Deep Learning',
    direction: 'left',
    evidence: 'Used across: Traffic Sign Detection \u00b7 DQN 2048',
    skills: ['PyTorch', 'TensorFlow', 'Neural Networks', 'CNNs', 'GPU / CUDA', 'Model Training'],
  },
  {
    id: 'gen-ai',
    name: 'Generative AI / LLM Systems',
    direction: 'right',
    evidence: 'Used across: VirtAI \u00b7 DEPI',
    skills: [
      'Generative AI',
      'LLMs',
      'RAG',
      'Prompt Engineering',
      'Embeddings',
      'Vector Databases',
      'LangChain',
      'LLM Integration',
      'Groq API',
      'ASR',
      'TTS',
      'Real-time AI Streaming',
    ],
  },
  {
    id: 'nlp',
    name: 'NLP',
    direction: 'left',
    skills: [
      'Transformers',
      'Hugging Face',
      'NLTK',
      'spaCy',
      'Contextual Embeddings',
      'N-gram Models',
      'Edit Distance',
      'Text Correction',
    ],
  },
  {
    id: 'computer-vision',
    name: 'Computer Vision',
    direction: 'right',
    evidence: 'Used across: Traffic Sign Detection \u00b7 Vehicle Detection',
    skills: [
      'OpenCV',
      'YOLOv8',
      'Object Detection',
      'Image Classification',
      'Image Preprocessing',
      'Data Augmentation',
      'ROI / Masking',
      'Real-time Vision',
      'Traffic Classification',
    ],
  },
  {
    id: 'rl',
    name: 'Reinforcement Learning',
    direction: 'left',
    evidence: 'Used across: DQN 2048',
    skills: [
      'Reinforcement Learning',
      'DQN',
      'Replay Buffer',
      'Target Networks',
      'Epsilon-Greedy',
      'RL Training / Evaluation',
    ],
  },
  {
    id: 'backend',
    name: 'Backend / Real-time',
    direction: 'right',
    evidence:
      'Used across: VirtAI \u00b7 Vehicle Detection \u00b7 Traffic Sign Detection \u00b7 DQN 2048',
    skills: [
      'FastAPI',
      'REST APIs',
      'WebSockets',
      'AsyncIO',
      'Pydantic',
      'Authentication',
      'Security',
      'API Design',
      'Clean Architecture',
      'Flask',
      'Uvicorn',
    ],
  },
  {
    id: 'frontend',
    name: 'Frontend / Interactive',
    direction: 'left',
    evidence: 'Used across: VirtAI',
    skills: [
      'React',
      'TypeScript',
      'Tailwind CSS',
      'Vite',
      'Zustand',
      'Three.js',
      'React Three Fiber',
      'Motion',
      'Responsive Design',
      'Frontend Performance',
      'SEO',
    ],
  },
  {
    id: 'data',
    name: 'Data / Databases',
    direction: 'right',
    skills: [
      'NumPy',
      'Pandas',
      'Dask',
      'SQL',
      'PostgreSQL',
      'MongoDB',
      'Redis',
      'Data Preprocessing',
      'Data Pipelines',
      'EDA',
      'Vector Databases',
    ],
  },
  {
    id: 'data-vis',
    name: 'Data Visualization',
    direction: 'left',
    skills: ['Matplotlib', 'Seaborn', 'Power BI'],
  },
  {
    id: 'time-series',
    name: 'Time Series',
    direction: 'right',
    skills: ['ARIMA', 'SARIMA', 'Prophet', 'Time Series Forecasting'],
  },
  {
    id: 'infra',
    name: 'Infrastructure / DevOps',
    direction: 'left',
    evidence: 'Used across: VirtAI',
    skills: [
      'Docker',
      'Docker Compose',
      'CI/CD',
      'GitHub Actions',
      'Linux',
      'DevOps',
      'Logging',
      'Deployment',
      'Make',
      'uv',
      'pnpm',
    ],
  },
  {
    id: 'quality',
    name: 'Engineering Quality',
    direction: 'right',
    skills: [
      'Pytest',
      'Vitest',
      'Playwright',
      'Locust',
      'Ruff',
      'Black',
      'Mypy',
      'ESLint',
      'Prettier',
      'Pre-commit',
      'pip-audit',
    ],
  },
];
